resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      name: source-controller
      version: v1
      kind: ServiceAccount
      namespace: flux-system
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: "hello@gcp.io"