# flux HelmRelease crd for installing nginx ingress controller chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec: nginx-ingress
    version: 2.3.x
    interval: 5h # this is for checking of a new chart
    sourceRef:
      kind: HelmRepository
      name: nginx
  releaseName: nginx
  interval: 1h #t his is for drifing of the helm created resources